export const SET_INITIAL_STATE = 'APP/SET_INITIAL_STATE'
export const SET_DRAWER        = 'APP/SET_DRAWER'
export const SET_LOADING       = 'APP/SET_LOADING'
export const SET_MINI_DRAWER   = 'APP/SET_MINI_DRAWER'
export const SET_SNACKBAR      = 'APP/SET_SNACKBAR'

// user
export const SET_USER                 = 'USER/SET_USER'
// province
export const SET_PROVINCES            = 'PROVINCE/SET_PROVINCES'
export const SET_PROVINCES_LOADING    = 'PROVINCE/SET_PROVINCES_LOADING'
export const SET_PROVINCES_PAGINATION = 'PROVINCE/SET_PROVINCES_PAGINATION'
// district
export const SET_DISTRICTS            = 'PROVINCE/SET_DISTRICTS'
export const SET_DISTRICTS_LOADING    = 'PROVINCE/SET_DISTRICTS_LOADING'
export const SET_DISTRICTS_PAGINATION = 'PROVINCE/SET_DISTRICTS_PAGINATION'
